# Generated by Django 4.2.6 on 2023-10-08 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='stock_disponible',
            field=models.IntegerField(),
        ),
    ]
