# Generated by Django 4.2.6 on 2023-10-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='nombre_region',
            field=models.CharField(max_length=50),
        ),
    ]
