# Generated by Django 4.2.4 on 2023-10-11 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha_visita',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
