# Generated by Django 4.2.4 on 2023-11-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='contador_reprogramaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visita',
            name='reprogramada',
            field=models.BooleanField(default=False),
        ),
    ]
