# Generated by Django 4.2.4 on 2023-10-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0002_visita_fecha_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='empleado_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
