# Generated by Django 4.2.4 on 2023-11-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0002_visita_contador_reprogramaciones_visita_reprogramada'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
