# Generated by Django 4.2.4 on 2023-11-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visita', '0003_visita_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
