# Generated by Django 4.2.4 on 2023-10-11 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=255)),
                ('cliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comuna', to='Cliente.cliente')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='Region.region')),
            ],
        ),
    ]
