# Generated by Django 4.2.6 on 2023-10-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Region', '0001_initial'),
        ('Comuna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comuna', to='Cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='Region.region'),
        ),
    ]
