# Generated by Django 4.2.4 on 2023-10-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comuna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comuna.comuna')),
            ],
        ),
    ]
