# Generated by Django 4.2.6 on 2023-10-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
